<template>
  <section class="kdbx-surface" @click="groupMenu = null">
    <form v-if="locked" class="kdbx-unlock" @submit.prevent="unlock">
      <div class="kdbx-unlock-panel">
        <h2>{{ displayFilename }}</h2><p>{{ t('kdbx.enterPassword') }}</p>
        <div class="kdbx-unlock-input"><el-input v-model="password" :type="unlockPasswordVisible ? 'text' : 'password'" autofocus autocomplete="current-password"><template #suffix><button class="kdbx-unlock-action" :title="unlockPasswordVisible ? t('kdbx.hidePassword') : t('kdbx.showPassword')" type="button" @mousedown.prevent @click="unlockPasswordVisible = !unlockPasswordVisible"><el-icon><Hide v-if="unlockPasswordVisible" /><View v-else /></el-icon></button><button class="kdbx-unlock-action" :title="t('kdbx.unlock')" type="submit" :disabled="unlocking || !password"><el-icon v-if="unlocking" class="is-loading"><Loading /></el-icon><span v-else class="kdbx-return-icon">&#8629;</span></button></template></el-input></div>
        <p v-if="error" class="kdbx-error">{{ error }}</p>
      </div>
    </form>

    <template v-else>
      <aside class="kdbx-groups">
        <div class="kdbx-pane-title kdbx-vault-title"><span :title="vault?.name">{{ vault?.name }}</span><div>
          <button :title="t('kdbx.newGroup')" type="button" @click.stop="createGroup()"><el-icon><FolderAdd /></el-icon></button>
          <button :title="t('kdbx.resetPassword')" type="button" @click.stop="openResetPassword"><el-icon><Key /></el-icon></button>
          <button :title="t('kdbx.lock')" type="button" @click.stop="lock"><el-icon><Lock /></el-icon></button>
        </div></div>
        <div class="kdbx-tree">
          <div class="kdbx-all-root">
            <button class="kdbx-all-toggle" type="button" :title="allItemsExpanded ? t('kdbx.collapse') : t('kdbx.expand')" @click.stop="toggleAllItems"><el-icon><ArrowDown v-if="allItemsExpanded" /><ArrowRight v-else /></el-icon></button>
            <button class="kdbx-nav-item" :class="{ active: selectedGroup === '' && !selectedRecycle && !selectedTag && !selectedUntagged }" :title="t('kdbx.allTags')" type="button" @click="selectAll"><el-icon><Tickets /></el-icon><span>{{ t('kdbx.allTags') }}</span><em>{{ normalEntries.length }}</em></button>
          </div>
          <div v-if="allItemsExpanded" class="kdbx-all-children">
            <div class="kdbx-tags">
              <button class="kdbx-nav-item kdbx-tag" :class="{ active: selectedUntagged }" :title="t('kdbx.untagged')" type="button" @click="selectUntagged"><el-icon><PriceTag /></el-icon><span>{{ t('kdbx.untagged') }}</span><em>{{ untaggedEntryCount }}</em></button>
              <button v-for="tag in availableTags" :key="tag" class="kdbx-nav-item kdbx-tag" :class="{ active: selectedTag === tag }" :title="tag" type="button" @click="selectTag(tag)"><el-icon><PriceTag /></el-icon><span>{{ tag }}</span><em>{{ tagEntryCount(tag) }}</em></button>
            </div>
          </div>
          <div v-for="group in visibleGroups" :key="group.id" class="kdbx-tree-row" :class="{ active: selectedGroup === group.id && !selectedRecycle }" :style="{ paddingLeft: `${8 + group.depth * 16}px` }" @contextmenu.prevent.stop="openGroupMenu(group, $event)">
            <button class="kdbx-tree-toggle" type="button" :title="expandedGroups.has(group.id) ? t('kdbx.collapse') : t('kdbx.expand')" @click.stop="toggleGroup(group.id)"><el-icon v-if="group.groups.length"><ArrowDown v-if="expandedGroups.has(group.id)" /><ArrowRight v-else /></el-icon></button>
            <button class="kdbx-tree-label" :title="groupDisplayName(group)" type="button" @click="selectGroup(group.id)"><el-icon><Folder /></el-icon><span>{{ groupDisplayName(group) }}</span><em>{{ group.entries }} / {{ group.totalEntries }}</em></button>
            <button class="kdbx-more" :title="t('kdbx.groupActions')" type="button" @click.stop="openGroupMenu(group, $event)"><el-icon><MoreFilled /></el-icon></button>
          </div>
        </div>
        <div class="kdbx-recycle"><button class="kdbx-nav-item" :class="{ active: selectedRecycle }" :title="t('kdbx.recycleBin')" type="button" @click="selectRecycle"><el-icon><DeleteFilled /></el-icon><span>{{ t('kdbx.recycleBin') }}</span><em>{{ recycleEntries.length }}</em></button><button v-if="recycleEntries.length" class="kdbx-more" :title="t('kdbx.emptyRecycleBin')" type="button" @click.stop="emptyRecycleBin"><el-icon><Delete /></el-icon></button></div>
      </aside>

      <main class="kdbx-entries">
        <div class="kdbx-toolbar"><el-input v-model="query" :placeholder="t('kdbx.search')" clearable><template #prefix><el-icon><Search /></el-icon></template></el-input><button :title="t('kdbx.searchOptions')" :class="{ active: showSearchOptions }" type="button" @click.stop="showSearchOptions = !showSearchOptions"><el-icon><Filter /></el-icon></button><button class="kdbx-export-selected" :title="t('kdbx.exportSelected', { count: selectedEntryIds.size })" :disabled="selectedEntryIds.size === 0 || exportingEntries" type="button" @click.stop="exportSelectedEntries"><el-icon :class="{ 'is-loading': exportingEntries }"><Loading v-if="exportingEntries" /><Download v-else /></el-icon><sup v-if="selectedEntryIds.size">{{ selectedEntryIds.size }}</sup></button><button :title="t('kdbx.newEntry')" :disabled="selectedRecycle" type="button" @click="createEntry"><el-icon><Plus /></el-icon></button></div>
        <div v-if="showSearchOptions" class="kdbx-search-options"><span>{{ t('kdbx.searchFields') }}</span><el-checkbox-group v-model="searchFields"><el-checkbox value="title">{{ t('kdbx.title') }}</el-checkbox><el-checkbox value="username">{{ t('kdbx.username') }}</el-checkbox><el-checkbox value="url">{{ t('kdbx.url') }}</el-checkbox><el-checkbox value="notes">{{ t('kdbx.notes') }}</el-checkbox></el-checkbox-group></div>
        <div v-for="entry in filteredEntries" :key="entry.id" class="kdbx-entry-row" :class="{ active: selectedEntryId === entry.id }"><el-checkbox :model-value="selectedEntryIds.has(entry.id)" :aria-label="t('kdbx.selectEntry')" @click.stop @change="toggleEntrySelection(entry.id)" /><button :title="entry.title || t('kdbx.untitled')" type="button" @click="selectEntry(entry.id)"><span class="kdbx-entry-title">{{ entry.title || t('kdbx.untitled') }}</span><span class="kdbx-entry-username">{{ entry.username || t('kdbx.noUsername') }}</span></button></div>
        <div v-if="filteredEntries.length === 0" class="kdbx-empty">{{ t('kdbx.noEntries') }}</div>
      </main>

      <aside class="kdbx-detail">
        <template v-if="draft">
          <div class="kdbx-detail-title"><div class="kdbx-breadcrumb" :title="entryPath"><span v-for="(part, index) in entryPathParts" :key="`${part}-${index}`">{{ part }}</span></div><div><button :title="t('kdbx.edit')" :disabled="draft.isRecycleBin" type="button" @click.stop="beginEdit"><el-icon><Edit /></el-icon></button><button :title="t('kdbx.copy')" type="button" @click.stop="copyEntry"><el-icon><DocumentCopy /></el-icon></button><button :title="t('kdbx.export')" :disabled="draft.isRecycleBin || exportingEntries" type="button" @click.stop="exportEntries([draft.id])"><el-icon><Download /></el-icon></button><button :title="draft.isRecycleBin ? t('kdbx.deletePermanently') : t('kdbx.delete')" type="button" @click="deleteEntry"><el-icon><Delete /></el-icon></button></div></div>
          <dl class="kdbx-entry-view"><dt>{{ t('kdbx.title') }}</dt><dd>{{ draft.title || t('kdbx.untitled') }}</dd><dt>{{ t('kdbx.username') }}</dt><dd>{{ draft.username || '-' }}</dd><dt>{{ t('kdbx.password') }}</dt><dd class="kdbx-password-view"><span>{{ showPassword ? viewPassword || '-' : viewPassword ? '••••••••' : '-' }}</span><button v-if="viewPassword" :title="showPassword ? t('kdbx.hidePassword') : t('kdbx.showPassword')" type="button" @click="showPassword = !showPassword"><el-icon><Hide v-if="showPassword" /><View v-else /></el-icon></button></dd><dt>{{ t('kdbx.url') }}</dt><dd>{{ draft.url || '-' }}</dd><dt>{{ t('kdbx.tags') }}</dt><dd><span v-for="tag in draft.tags" :key="tag" class="kdbx-tag-chip">{{ tag }}</span><span v-if="!draft.tags.length">-</span></dd><dt>{{ t('kdbx.notes') }}</dt><dd>{{ draft.notes || '-' }}</dd></dl>
          <section v-if="viewCustomFields.length" class="kdbx-section"><div class="kdbx-section-title"><strong>{{ t('kdbx.customFields') }}</strong></div><dl class="kdbx-entry-view kdbx-custom-field-view"><template v-for="field in viewCustomFields" :key="field.key"><dt>{{ field.key }}</dt><dd>{{ field.protected ? '••••••••' : field.value || '-' }}</dd></template></dl></section>
          <section class="kdbx-section"><div class="kdbx-section-title"><strong>{{ t('kdbx.attachments') }}</strong></div><div v-if="viewAttachments.length === 0" class="kdbx-section-empty">{{ t('kdbx.noAttachments') }}</div><div v-for="attachment in viewAttachments" :key="attachment.id" class="kdbx-attachment"><div><el-icon><Document /></el-icon><span>{{ attachment.name }}</span><em>{{ formatSize(attachment.size) }}</em></div><button v-if="isPreviewable(attachment)" :title="t('kdbx.previewAttachment')" type="button" @click="previewAttachment(attachment)"><el-icon><View /></el-icon></button><button :title="t('kdbx.downloadAttachment')" type="button" @click="downloadAttachment(attachment)"><el-icon><Download /></el-icon></button></div></section>
          <section v-if="draft.historyCount" class="kdbx-section kdbx-history"><div class="kdbx-section-title"><strong>{{ t('kdbx.history') }} ({{ draft.historyCount }})</strong></div><div v-for="item in draft.history" :key="item.index" class="kdbx-history-row"><div><strong>{{ item.title || t('kdbx.untitled') }}</strong><span>{{ item.updatedAt ? new Date(item.updatedAt).toLocaleString() : '' }}</span></div><button type="button" @click="viewHistory(item.index)">{{ t('kdbx.viewHistory') }}</button><button type="button" @click="restoreHistory(item.index)">{{ t('kdbx.restoreHistory') }}</button><button class="kdbx-history-delete" :title="t('kdbx.deleteHistory')" type="button" @click="deleteHistory(item.index)"><el-icon><Delete /></el-icon></button></div></section>
        </template>
        <div v-else class="kdbx-empty">{{ t('kdbx.selectEntry') }}</div>
      </aside>
    </template>

    <div v-if="groupMenu" class="kdbx-group-menu" :style="{ left: `${groupMenu.x}px`, top: `${groupMenu.y}px` }" @click.stop><button type="button" @click="createGroup(groupMenu.group.id)"><el-icon><FolderAdd /></el-icon>{{ t('kdbx.newGroup') }}</button><button type="button" @click="importEntries(groupMenu.group.id)"><el-icon><Upload /></el-icon>{{ t('kdbx.import') }}</button><template v-if="!groupMenu.group.isRoot"><button type="button" @click="renameGroup(groupMenu.group)"><el-icon><Edit /></el-icon>{{ t('kdbx.renameGroup') }}</button><button type="button" @click="deleteGroup(groupMenu.group)"><el-icon><Delete /></el-icon>{{ t('kdbx.delete') }}</button></template></div>
    <el-dialog v-model="historyDialogVisible" :title="t('kdbx.historyVersion')" width="620px"><template v-if="historyPreview"><dl class="kdbx-history-preview"><dt>{{ t('kdbx.title') }}</dt><dd>{{ historyPreview.title || t('kdbx.untitled') }}</dd><dt>{{ t('kdbx.username') }}</dt><dd>{{ historyPreview.username }}</dd><dt>{{ t('kdbx.url') }}</dt><dd>{{ historyPreview.url }}</dd><dt>{{ t('kdbx.tags') }}</dt><dd>{{ historyPreview.tags.join(', ') }}</dd><dt>{{ t('kdbx.notes') }}</dt><dd>{{ historyPreview.notes }}</dd><dt>{{ t('kdbx.customFields') }}</dt><dd>{{ historyPreview.fields.filter(field => !standardFieldKeys.includes(field.key)).map(field => `${field.key}: ${field.value}`).join('\n') || '-' }}</dd><dt>{{ t('kdbx.attachments') }}</dt><dd>{{ historyPreview.attachments.map(attachment => attachment.name).join(', ') || '-' }}</dd></dl></template></el-dialog>
    <el-dialog v-model="resetPasswordVisible" class="kdbx-reset-password-dialog" :title="t('kdbx.resetPassword')" width="440px" :close-on-click-modal="false" @closed="clearResetPassword">
      <el-form label-position="top" @submit.prevent="resetVaultPassword">
        <el-form-item :label="t('kdbx.currentPassword')"><el-input v-model="resetCurrentPassword" :class="{ 'is-password-invalid': currentPasswordInvalid }" type="password" show-password autocomplete="current-password" /></el-form-item>
        <el-form-item :label="t('kdbx.newPassword')"><el-input v-model="resetNewPassword" :class="{ 'is-password-invalid': newPasswordInvalid }" type="password" show-password autocomplete="new-password" /><div class="kdbx-password-rule" :class="{ error: newPasswordInvalid }">{{ t('kdbx.passwordRule') }}</div></el-form-item>
        <el-form-item :label="t('kdbx.confirmPassword')"><el-input v-model="resetConfirmPassword" :class="{ 'is-password-invalid': resetPasswordMismatch }" type="password" show-password autocomplete="new-password" /><div v-if="resetPasswordMismatch" class="kdbx-password-rule error">{{ t('kdbx.passwordMismatch') }}</div></el-form-item>
      </el-form>
      <template #footer><el-button @click="resetPasswordVisible = false">{{ t('common.cancel') }}</el-button><el-button type="primary" :loading="resettingPassword" @click="resetVaultPassword">{{ t('kdbx.resetPassword') }}</el-button></template>
    </el-dialog>
    <el-dialog v-model="attachmentPreviewVisible" :title="attachmentPreviewName" width="min(860px, calc(100vw - 48px))" @closed="clearAttachmentPreview"><img v-if="attachmentPreviewUrl" class="kdbx-attachment-preview" :src="attachmentPreviewUrl" :alt="attachmentPreviewName" /></el-dialog>
    <el-dialog v-if="editDraft" v-model="editing" class="kdbx-edit-dialog" :title="editEntryPath" width="min(760px, calc(100vw - 48px))" :close-on-click-modal="false" @closed="cancelEdit">
      <div class="kdbx-edit-form">
        <label>{{ t('kdbx.title') }}<el-input v-model="editDraft.title" /></label>
        <label>{{ t('kdbx.username') }}<el-input v-model="editDraft.username" /></label>
        <label>{{ t('kdbx.password') }}<el-input v-model="passwordField" type="password" show-password /></label>
        <label>{{ t('kdbx.url') }}<el-input v-model="editDraft.url" /></label>
        <label>{{ t('kdbx.tags') }}<el-select v-model="editDraft.tags" multiple filterable allow-create default-first-option><el-option v-for="tag in vault?.tags" :key="tag" :label="tag" :value="tag" /></el-select></label>
        <label>{{ t('kdbx.notes') }}<el-input v-model="editDraft.notes" type="textarea" :rows="4" /></label>
        <section class="kdbx-section"><div class="kdbx-section-title"><strong>{{ t('kdbx.customFields') }}</strong><button :title="t('kdbx.addCustomField')" type="button" @click="addCustomField"><el-icon><Plus /></el-icon></button></div><div v-for="field in customFields" :key="field.id" class="kdbx-custom-field"><el-input v-model="field.key" :placeholder="t('kdbx.fieldName')" /><el-input v-model="field.value" :type="field.protected ? 'password' : 'text'" :show-password="field.protected" :placeholder="t('kdbx.fieldValue')" /><el-checkbox v-model="field.protected" :title="t('kdbx.protectedField')"><el-icon><Lock /></el-icon></el-checkbox><button :title="t('kdbx.removeCustomField')" type="button" @click="removeCustomField(field.id)"><el-icon><Delete /></el-icon></button></div></section>
        <section class="kdbx-section"><div class="kdbx-section-title"><strong>{{ t('kdbx.attachments') }}</strong><button :title="t('kdbx.addAttachment')" type="button" @click="attachmentInput?.click()"><el-icon><Paperclip /></el-icon></button></div><input ref="attachmentInput" class="kdbx-file-input" type="file" @change="addAttachment" /><div v-if="draftAttachments.length === 0" class="kdbx-section-empty">{{ t('kdbx.noAttachments') }}</div><div v-for="attachment in draftAttachments" :key="attachment.id" class="kdbx-attachment"><div><el-icon><Document /></el-icon><span>{{ attachment.name }}</span><em>{{ formatSize(attachment.size) }}</em></div><button v-if="isPreviewable(attachment)" :title="t('kdbx.previewAttachment')" type="button" @click="previewAttachment(attachment)"><el-icon><View /></el-icon></button><button :title="t('kdbx.downloadAttachment')" type="button" @click="downloadAttachment(attachment)"><el-icon><Download /></el-icon></button><button :title="t('kdbx.removeAttachment')" type="button" @click="removeAttachment(attachment)"><el-icon><Delete /></el-icon></button></div></section>
      </div>
      <template #footer><el-button @click="cancelEdit">{{ t('common.cancel') }}</el-button><el-button type="primary" :loading="savingEntry" @click="saveEntry">{{ t('kdbx.save') }}</el-button></template>
    </el-dialog>
  </section>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, toRaw, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowDown, ArrowRight, Delete, DeleteFilled, Document, DocumentCopy, Download, Edit, Filter, Folder, FolderAdd, Hide, Key, Loading, Lock, MoreFilled, Paperclip, Plus, PriceTag, Search, Tickets, Upload, View } from '@element-plus/icons-vue'
import { useI18n } from 'vue-i18n'
import { useEditorStore } from '@/store/editor'
import type { KdbxEntryDetail, KdbxEntryInput, KdbxEntryRevision, KdbxField, KdbxGroupSummary, KdbxVaultSnapshot } from '@shared/types/kdbx'
import { isKdbxPasswordValid, KDBX_PASSWORD_PATTERN } from '@shared/kdbxPassword'

interface FlatGroup extends KdbxGroupSummary { depth: number }
interface CustomField extends KdbxField { id: string }
interface GroupMenuState { group: FlatGroup; x: number; y: number }
interface AttachmentDraft { id: string; name: string; size: number; data?: ArrayBuffer; removed: boolean }
const standardFieldKeys = ['Title', 'UserName', 'URL', 'Notes', 'Password']
const { t } = useI18n()
const errorMessage = (reason: unknown, fallback: string): string => {
  const message = reason instanceof Error ? reason.message : typeof reason === 'string' ? reason : ''
  return message.replace(/^Error invoking remote method '[^']+':\s*(?:Error:\s*)?/, '').replace(/^Error:\s*/, '') || fallback
}
const { currentFile } = storeToRefs(useEditorStore())
const vault = ref<KdbxVaultSnapshot | null>(null)
const locked = ref(true); const password = ref(''); const error = ref(''); const unlocking = ref(false); const unlockPasswordVisible = ref(false)
const query = ref(''); const searchFields = ref(['title', 'username', 'url', 'notes']); const showSearchOptions = ref(false)
const selectedGroup = ref(''); const selectedTag = ref(''); const selectedUntagged = ref(false); const selectedRecycle = ref(false); const selectedEntryId = ref(''); const selectedEntryIds = ref(new Set<string>()); const draft = ref<KdbxEntryDetail | null>(null); const editDraft = ref<KdbxEntryDetail | null>(null); const passwordField = ref(''); const savingEntry = ref(false); const exportingEntries = ref(false); const editing = ref(false); const newEntry = ref(false); const showPassword = ref(false)
const expandedGroups = ref(new Set<string>()); const allItemsExpanded = ref(true); const groupMenu = ref<GroupMenuState | null>(null); const attachmentInput = ref<HTMLInputElement | null>(null); const historyDialogVisible = ref(false); const historyPreview = ref<KdbxEntryRevision | null>(null); const attachmentPreviewVisible = ref(false); const attachmentPreviewUrl = ref(''); const attachmentPreviewName = ref('')
const resetPasswordVisible = ref(false); const resettingPassword = ref(false); const resetAttempted = ref(false); const resetCurrentPassword = ref(''); const resetNewPassword = ref(''); const resetConfirmPassword = ref('')
const customFields = ref<CustomField[]>([])
const attachmentDrafts = ref<AttachmentDraft[]>([])
let nextCustomFieldId = 0
let nextAttachmentDraftId = 0
const filePath = computed(() => currentFile.value?.isKdbx ? currentFile.value.pathname : '')
const displayFilename = computed(() => currentFile.value?.filename.replace(/\.kdbx$/i, '') ?? '')
const normalEntries = computed(() => (vault.value?.entries || []).filter(entry => !entry.isRecycleBin))
const recycleEntries = computed(() => (vault.value?.entries || []).filter(entry => entry.isRecycleBin))
const entryTags = (entry: KdbxVaultSnapshot['entries'][number]): string[] => (entry.tags || []).filter(tag => tag.trim())
const availableTags = computed(() => (vault.value?.tags || []).filter(tag => tag.trim()))
const tagEntryCount = (tag: string): number => normalEntries.value.filter(entry => entryTags(entry).includes(tag)).length
const untaggedEntryCount = computed(() => normalEntries.value.filter(entry => entryTags(entry).length === 0).length)
const flatGroups = computed<FlatGroup[]>(() => { const flatten = (groups: KdbxGroupSummary[], depth = 0): FlatGroup[] => groups.flatMap(group => [{ ...group, depth }, ...flatten(group.groups, depth + 1)]); return flatten(vault.value?.groups || []) })
const visibleGroups = computed<FlatGroup[]>(() => { const visible = (groups: KdbxGroupSummary[], depth = 0): FlatGroup[] => groups.flatMap((group) => { const current: FlatGroup = { ...group, depth }; return expandedGroups.value.has(group.id) ? [current, ...visible(group.groups, depth + 1)] : [current] }); return visible(vault.value?.groups || []) })
const groupDisplayName = (group: KdbxGroupSummary): string => group.isRoot ? t('kdbx.allGroups') : group.name
const displayGroupPath = (path: string[]): string[] => path.map((name, index) => index === 0 ? t('kdbx.allGroups') : name)
const filteredEntries = computed(() => { const value = query.value.trim().toLocaleLowerCase(); return (selectedRecycle.value ? recycleEntries.value : normalEntries.value).filter((entry) => { const tags = entryTags(entry); if (!selectedRecycle.value && selectedGroup.value && entry.groupId !== selectedGroup.value) return false; if (!selectedRecycle.value && selectedTag.value && !tags.includes(selectedTag.value)) return false; if (!selectedRecycle.value && selectedUntagged.value && tags.length > 0) return false; if (!value) return true; const fields: Record<string, string> = { title: entry.title, username: entry.username, url: entry.url, notes: entry.notes }; return searchFields.value.some(field => fields[field]?.toLocaleLowerCase().includes(value)) || tags.some(tag => tag.toLocaleLowerCase().includes(value)) }) })
const entryPathParts = computed(() => { if (!draft.value) return []; const vaultName = vault.value?.name || t('kdbx.vault'); const groups = displayGroupPath(draft.value.groupPath).filter((name, index) => index !== 0 || name !== vaultName); return [vaultName, ...groups, draft.value.title || t('kdbx.untitled')] })
const entryPath = computed(() => entryPathParts.value.join(' / '))
const editEntryPath = computed(() => { if (!editDraft.value) return ''; const vaultName = vault.value?.name || t('kdbx.vault'); const groups = displayGroupPath(editDraft.value.groupPath).filter((name, index) => index !== 0 || name !== vaultName); return [vaultName, ...groups, editDraft.value.title || t('kdbx.untitled')].join(' / ') })
const draftAttachments = computed(() => attachmentDrafts.value.filter(attachment => !attachment.removed))
const viewPassword = computed(() => draft.value?.fields.find(field => field.key === 'Password')?.value || '')
const viewCustomFields = computed(() => (draft.value?.fields || []).filter(field => !standardFieldKeys.includes(field.key)))
const viewAttachments = computed<AttachmentDraft[]>(() => (draft.value?.attachments || []).map(attachment => ({ ...attachment, id: `view-${attachment.name}`, removed: false })))
const currentPasswordInvalid = computed(() => resetAttempted.value && !resetCurrentPassword.value)
const newPasswordInvalid = computed(() => (resetNewPassword.value.length > 0 && !isKdbxPasswordValid(resetNewPassword.value)) || (resetAttempted.value && !isKdbxPasswordValid(resetNewPassword.value)))
const resetPasswordMismatch = computed(() => resetConfirmPassword.value.length > 0 && resetNewPassword.value !== resetConfirmPassword.value)
const expandAllGroups = (): void => { expandedGroups.value = new Set(flatGroups.value.map(group => group.id)) }
const refresh = async(pathname = filePath.value): Promise<void> => { if (!pathname || locked.value) return; vault.value = await window.electron.ipcRenderer.invoke('mt::kdbx::snapshot', pathname); expandAllGroups() }
const unlock = async(): Promise<void> => { if (!filePath.value || !password.value) return; unlocking.value = true; error.value = ''; try { vault.value = await window.electron.ipcRenderer.invoke('mt::kdbx::unlock', filePath.value, password.value); locked.value = false; password.value = ''; unlockPasswordVisible.value = false; expandAllGroups() } catch (err) { const message = err instanceof Error ? err.message : ''; error.value = /InvalidKey/i.test(message) ? t('kdbx.invalidPassword') : t('kdbx.unlockFailed') } finally { unlocking.value = false } }
const clearCustomFields = (): void => { customFields.value = [] }
const loadCustomFields = (detail: KdbxEntryDetail): void => { customFields.value = detail.fields.filter(field => !standardFieldKeys.includes(field.key)).map(field => ({ ...field, id: `custom-${nextCustomFieldId++}` })) }
const loadAttachments = (detail: KdbxEntryDetail): void => { attachmentDrafts.value = detail.attachments.map(attachment => ({ ...attachment, id: `attachment-${nextAttachmentDraftId++}`, removed: false })) }
const clearAttachmentPreview = (): void => { if (attachmentPreviewUrl.value.startsWith('blob:')) URL.revokeObjectURL(attachmentPreviewUrl.value); attachmentPreviewUrl.value = ''; attachmentPreviewName.value = '' }
const clearEditDraft = (): void => { editDraft.value = null; passwordField.value = ''; editing.value = false; newEntry.value = false; clearCustomFields(); attachmentDrafts.value = []; clearAttachmentPreview() }
const clearDraft = (): void => { draft.value = null; selectedEntryId.value = ''; showPassword.value = false; clearEditDraft() }
const lock = async(): Promise<void> => { const pathname = filePath.value; if (!pathname) return; await window.electron.ipcRenderer.invoke('mt::kdbx::lock', pathname); if (pathname !== filePath.value) return; vault.value = null; clearDraft(); password.value = ''; unlockPasswordVisible.value = false; locked.value = true }
const clearResetPassword = (): void => { resetAttempted.value = false; resetCurrentPassword.value = ''; resetNewPassword.value = ''; resetConfirmPassword.value = '' }
const openResetPassword = (): void => { clearResetPassword(); resetPasswordVisible.value = true }
const resetVaultPassword = async(): Promise<void> => { if (!filePath.value || resettingPassword.value) return; resetAttempted.value = true; if (!resetCurrentPassword.value || !isKdbxPasswordValid(resetNewPassword.value) || resetNewPassword.value !== resetConfirmPassword.value) return; resettingPassword.value = true; try { await window.electron.ipcRenderer.invoke('mt::kdbx::reset-password', filePath.value, resetCurrentPassword.value, resetNewPassword.value); resetPasswordVisible.value = false; ElMessage.success(t('kdbx.passwordReset')) } catch (error) { ElMessage.error(errorMessage(error, t('kdbx.resetPasswordFailed'))) } finally { resettingPassword.value = false } }
const clearEntrySelection = (): void => { selectedEntryIds.value = new Set() }
const toggleEntrySelection = (id: string): void => { const next = new Set(selectedEntryIds.value); next.has(id) ? next.delete(id) : next.add(id); selectedEntryIds.value = next }
const selectAll = (): void => { selectedGroup.value = ''; selectedTag.value = ''; selectedUntagged.value = false; selectedRecycle.value = false; clearEntrySelection() }
const selectRecycle = (): void => { selectedGroup.value = ''; selectedTag.value = ''; selectedUntagged.value = false; selectedRecycle.value = true; selectedEntryId.value = ''; clearEntrySelection(); clearDraft() }
const selectGroup = (id: string): void => { selectedGroup.value = id; selectedTag.value = ''; selectedUntagged.value = false; selectedRecycle.value = false; clearEntrySelection() }
const selectTag = (tag: string): void => { selectedTag.value = selectedTag.value === tag ? '' : tag; selectedUntagged.value = false; selectedGroup.value = ''; selectedRecycle.value = false; clearEntrySelection() }
const selectUntagged = (): void => { selectedUntagged.value = !selectedUntagged.value; selectedTag.value = ''; selectedGroup.value = ''; selectedRecycle.value = false; clearEntrySelection() }
const toggleAllItems = (): void => { allItemsExpanded.value = !allItemsExpanded.value }
const toggleGroup = (id: string): void => { const next = new Set(expandedGroups.value); next.has(id) ? next.delete(id) : next.add(id); expandedGroups.value = next }
const openGroupMenu = (group: FlatGroup, event: MouseEvent): void => { groupMenu.value = { group, x: event.clientX, y: event.clientY } }
const groupPathFor = (targetId: string, groups = vault.value?.groups || [], ancestors: string[] = []): string[] => { for (const group of groups) { const current = [...ancestors, groupDisplayName(group)]; if (group.id === targetId) return current; const found = groupPathFor(targetId, group.groups, current); if (found.length) return found } return [] }
const selectEntry = async(id: string): Promise<void> => { if (!filePath.value) return; if (editing.value && id !== selectedEntryId.value) { try { await ElMessageBox.confirm(t('kdbx.discardChangesConfirm'), t('kdbx.cancelEdit'), { confirmButtonText: t('common.ok'), cancelButtonText: t('common.cancel'), type: 'warning' }) } catch { return } clearEditDraft() } const detail = await window.electron.ipcRenderer.invoke('mt::kdbx::entry', filePath.value, id); if (!detail) return; selectedEntryId.value = id; draft.value = detail; showPassword.value = false }
const toInput = (): KdbxEntryInput => { const active = editDraft.value!; const fields = customFields.value.filter(field => field.key.trim()).map(field => ({ key: field.key.trim(), value: field.value, protected: field.protected })); fields.push({ key: 'Password', value: passwordField.value, protected: true }); return { groupId: active.groupId || selectedGroup.value, title: active.title, username: active.username, url: active.url, notes: active.notes, tags: [...active.tags], fields, attachments: { add: attachmentDrafts.value.filter(attachment => attachment.data && !attachment.removed).map(attachment => ({ name: attachment.name, data: attachment.data! })), remove: attachmentDrafts.value.filter(attachment => attachment.removed && !attachment.data).map(attachment => attachment.name) } } }
const createGroup = async(parentId = selectedGroup.value): Promise<void> => { if (!filePath.value) return; groupMenu.value = null; try { const { value } = await ElMessageBox.prompt(t('kdbx.groupName'), t('kdbx.newGroup'), { confirmButtonText: t('common.ok'), cancelButtonText: t('common.cancel'), inputPattern: /\S/, inputErrorMessage: t('kdbx.groupNameRequired') }); vault.value = await window.electron.ipcRenderer.invoke('mt::kdbx::create-group', filePath.value, parentId, value); expandAllGroups() } catch { /* cancelled */ } }
const renameGroup = async(group: FlatGroup): Promise<void> => { if (!filePath.value) return; groupMenu.value = null; try { const { value } = await ElMessageBox.prompt(t('kdbx.groupName'), t('kdbx.renameGroup'), { inputValue: group.name, confirmButtonText: t('common.ok'), cancelButtonText: t('common.cancel'), inputPattern: /\S/, inputErrorMessage: t('kdbx.groupNameRequired') }); vault.value = await window.electron.ipcRenderer.invoke('mt::kdbx::rename-group', filePath.value, group.id, value) } catch { /* cancelled */ } }
const deleteGroup = async(group: FlatGroup): Promise<void> => { if (!filePath.value) return; groupMenu.value = null; try { await ElMessageBox.confirm(t('kdbx.deleteGroupConfirm', { name: group.name }), t('kdbx.delete'), { confirmButtonText: t('common.ok'), cancelButtonText: t('common.cancel'), type: 'warning' }); vault.value = await window.electron.ipcRenderer.invoke('mt::kdbx::delete-group', filePath.value, group.id); if (selectedGroup.value === group.id) selectAll() } catch { /* cancelled */ } }
const emptyRecycleBin = async(): Promise<void> => { if (!filePath.value) return; try { await ElMessageBox.confirm(t('kdbx.emptyRecycleBinConfirm'), t('kdbx.emptyRecycleBin'), { confirmButtonText: t('kdbx.deletePermanently'), cancelButtonText: t('common.cancel'), type: 'warning' }); vault.value = await window.electron.ipcRenderer.invoke('mt::kdbx::empty-recycle-bin', filePath.value); selectedEntryId.value = ''; clearDraft() } catch { /* cancelled */ } }
const createEntry = async(): Promise<void> => { if (!filePath.value || selectedRecycle.value) return; if (editing.value) { try { await ElMessageBox.confirm(t('kdbx.discardChangesConfirm'), t('kdbx.cancelEdit'), { confirmButtonText: t('common.ok'), cancelButtonText: t('common.cancel'), type: 'warning' }) } catch { return } clearEditDraft() } const groupId = selectedGroup.value || flatGroups.value[0]?.id || ''; if (!groupId) return; editDraft.value = { id: '', groupId, title: '', username: '', url: '', notes: '', tags: [], updatedAt: null, groupPath: groupPathFor(groupId), isRecycleBin: false, fields: [], attachments: [], historyCount: 0, history: [] }; passwordField.value = ''; clearCustomFields(); attachmentDrafts.value = []; newEntry.value = true; editing.value = true }
const beginEdit = (): void => { if (!draft.value) return; editDraft.value = structuredClone(toRaw(draft.value)); passwordField.value = viewPassword.value; loadCustomFields(editDraft.value); loadAttachments(editDraft.value); newEntry.value = false; editing.value = true }
const cancelEdit = (): void => { clearEditDraft() }
const saveEntry = async(): Promise<void> => { if (!filePath.value || !editDraft.value || savingEntry.value) return; savingEntry.value = true; try { const detail = newEntry.value ? await window.electron.ipcRenderer.invoke('mt::kdbx::create-entry', filePath.value, toInput()) : await window.electron.ipcRenderer.invoke('mt::kdbx::commit-entry', filePath.value, editDraft.value.id, toInput()); draft.value = detail; selectedEntryId.value = detail.id; showPassword.value = false; clearEditDraft(); await refresh(); ElMessage.success(t('kdbx.saved')) } catch (err) { ElMessage.error(errorMessage(err, t('kdbx.saveFailed'))) } finally { savingEntry.value = false } }
const deleteEntry = async(): Promise<void> => { if (!filePath.value || !draft.value) return; const permanent = draft.value.isRecycleBin; try { await ElMessageBox.confirm(permanent ? t('kdbx.deletePermanentlyConfirm') : t('kdbx.moveToRecycleBinConfirm'), permanent ? t('kdbx.deletePermanently') : t('kdbx.delete'), { confirmButtonText: t('common.ok'), cancelButtonText: t('common.cancel'), type: 'warning' }); vault.value = await window.electron.ipcRenderer.invoke('mt::kdbx::delete-entry', filePath.value, draft.value.id); clearDraft() } catch { /* cancelled */ } }
const addCustomField = (): void => { if (!editDraft.value) return; customFields.value.push({ id: `custom-${nextCustomFieldId++}`, key: '', value: '', protected: false }) }
const removeCustomField = (id: string): void => { customFields.value = customFields.value.filter(field => field.id !== id) }
const addAttachment = async(event: Event): Promise<void> => { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!editDraft.value || !file) return; try { attachmentDrafts.value.push({ id: `attachment-${nextAttachmentDraftId++}`, name: file.name, size: file.size, data: await file.arrayBuffer(), removed: false }); ElMessage.success(t('kdbx.attachmentAdded')) } catch (err) { ElMessage.error(errorMessage(err, t('kdbx.attachmentFailed'))) } finally { input.value = '' } }
const removeAttachment = async(attachment: AttachmentDraft): Promise<void> => { try { await ElMessageBox.confirm(t('kdbx.removeAttachmentConfirm', { name: attachment.name }), t('kdbx.removeAttachment'), { confirmButtonText: t('common.ok'), cancelButtonText: t('common.cancel'), type: 'warning' }); if (attachment.data) attachmentDrafts.value = attachmentDrafts.value.filter(item => item.id !== attachment.id); else attachment.removed = true } catch { /* cancelled */ } }
const readAttachment = async(attachment: AttachmentDraft): Promise<ArrayBuffer> => { if (attachment.data) return attachment.data; if (!filePath.value || !draft.value) throw new Error(t('kdbx.attachmentFailed')); return window.electron.ipcRenderer.invoke('mt::kdbx::read-attachment', filePath.value, draft.value.id, attachment.name) }
const attachmentMimeType = (name: string): string => { const extension = name.split('.').pop()?.toLowerCase(); return ({ avif: 'image/avif', gif: 'image/gif', jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', svg: 'image/svg+xml', webp: 'image/webp' })[extension || ''] || 'application/octet-stream' }
const downloadAttachment = async(attachment: AttachmentDraft): Promise<void> => { try { const data = await readAttachment(attachment); const link = document.createElement('a'); const url = URL.createObjectURL(new Blob([data], { type: attachmentMimeType(attachment.name) })); link.href = url; link.download = attachment.name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0) } catch (err) { ElMessage.error(errorMessage(err, t('kdbx.attachmentFailed'))) } }
const isPreviewable = (attachment: AttachmentDraft): boolean => /\.(avif|gif|jpe?g|png|svg|webp)$/i.test(attachment.name)
const previewAttachment = async(attachment: AttachmentDraft): Promise<void> => { try { clearAttachmentPreview(); if (attachment.data) attachmentPreviewUrl.value = URL.createObjectURL(new Blob([attachment.data], { type: attachmentMimeType(attachment.name) })); else { if (!filePath.value || !draft.value) throw new Error(t('kdbx.attachmentFailed')); attachmentPreviewUrl.value = await window.electron.ipcRenderer.invoke('mt::kdbx::preview-attachment', filePath.value, draft.value.id, attachment.name) } attachmentPreviewName.value = attachment.name; attachmentPreviewVisible.value = true } catch (err) { ElMessage.error(errorMessage(err, t('kdbx.attachmentFailed'))) } }
const copyEntry = (): void => { if (!draft.value) return; const lines = [`${t('kdbx.title')}: ${draft.value.title}`, `${t('kdbx.username')}: ${draft.value.username}`, `${t('kdbx.password')}: ${viewPassword.value}`, `${t('kdbx.url')}: ${draft.value.url}`, `${t('kdbx.tags')}: ${draft.value.tags.join(', ')}`, `${t('kdbx.notes')}: ${draft.value.notes}`, ...viewCustomFields.value.map(field => `${field.key}: ${field.value}`)]; window.electron.clipboard.writeText(lines.join('\n')); ElMessage.success(t('kdbx.copied')) }
const exportEntries = async(entryIds: string[]): Promise<void> => { if (!filePath.value || entryIds.length === 0 || exportingEntries.value) return; try { const { value } = await ElMessageBox.prompt(t('kdbx.extractionCode'), t('kdbx.exportEntries'), { confirmButtonText: t('kdbx.export'), cancelButtonText: t('common.cancel'), inputType: 'password', inputPattern: KDBX_PASSWORD_PATTERN, inputErrorMessage: t('kdbx.passwordRule') }); exportingEntries.value = true; const exported = await window.electron.ipcRenderer.invoke('mt::kdbx::export-entries', filePath.value, entryIds, value); if (exported) ElMessage.success(t('kdbx.exported')) } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error(errorMessage(error, t('kdbx.exportFailed'))) } finally { exportingEntries.value = false } }
const exportSelectedEntries = (): Promise<void> => exportEntries([...selectedEntryIds.value])
const importEntries = async(groupId: string): Promise<void> => { if (!filePath.value) return; groupMenu.value = null; try { const importFilePath = await window.electron.ipcRenderer.invoke('mt::kdbx::select-import-file'); if (!importFilePath) return; const { value } = await ElMessageBox.prompt(t('kdbx.extractionCode'), t('kdbx.importEntries'), { confirmButtonText: t('kdbx.import'), cancelButtonText: t('common.cancel'), inputType: 'password', inputPattern: /\S/, inputErrorMessage: t('kdbx.extractionCodeRequired') }); vault.value = await window.electron.ipcRenderer.invoke('mt::kdbx::import-entries', filePath.value, groupId, importFilePath, value); expandAllGroups(); ElMessage.success(t('kdbx.imported')) } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error(errorMessage(error, t('kdbx.importFailed'))) } }
const formatSize = (size: number): string => size < 1024 ? `${size} B` : size < 1024 * 1024 ? `${(size / 1024).toFixed(1)} KB` : `${(size / (1024 * 1024)).toFixed(1)} MB`
const viewHistory = async(historyIndex: number): Promise<void> => { if (!filePath.value || !draft.value) return; try { historyPreview.value = await window.electron.ipcRenderer.invoke('mt::kdbx::history-entry', filePath.value, draft.value.id, historyIndex); historyDialogVisible.value = true } catch (err) { ElMessage.error(errorMessage(err, t('kdbx.historyFailed'))) } }
const restoreHistory = async(historyIndex: number): Promise<void> => { if (!filePath.value || !draft.value) return; try { await ElMessageBox.confirm(t('kdbx.restoreHistoryConfirm'), t('kdbx.restoreHistory'), { confirmButtonText: t('common.ok'), cancelButtonText: t('common.cancel'), type: 'warning' }); const detail = await window.electron.ipcRenderer.invoke('mt::kdbx::restore-history', filePath.value, draft.value.id, historyIndex); draft.value = detail; showPassword.value = false; await refresh(); ElMessage.success(t('kdbx.restored')) } catch { /* cancelled */ } }
const deleteHistory = async(historyIndex: number): Promise<void> => { if (!filePath.value || !draft.value) return; try { await ElMessageBox.confirm(t('kdbx.deleteHistoryConfirm'), t('kdbx.deleteHistory'), { confirmButtonText: t('kdbx.deletePermanently'), cancelButtonText: t('common.cancel'), type: 'warning' }); draft.value = await window.electron.ipcRenderer.invoke('mt::kdbx::delete-history', filePath.value, draft.value.id, historyIndex); await refresh() } catch { /* cancelled */ } }
const activate = async(pathname: string): Promise<void> => { locked.value = true; vault.value = null; clearDraft(); password.value = ''; unlockPasswordVisible.value = false; error.value = ''; selectedGroup.value = ''; selectedTag.value = ''; selectedUntagged.value = false; selectedRecycle.value = false; if (!pathname) return; try { const value = await window.electron.ipcRenderer.invoke('mt::kdbx::snapshot', pathname); if (pathname === filePath.value) { vault.value = value; locked.value = false; expandAllGroups() } } catch { /* locked vaults do not expose decrypted data */ } }
watch(filePath, next => { void activate(next) }, { immediate: true })
onMounted(() => window.electron.ipcRenderer.on('mt::kdbx-lock', lock))
onBeforeUnmount(() => { window.electron.ipcRenderer.removeAllListeners('mt::kdbx-lock'); clearAttachmentPreview() })
</script>

<style scoped>
.kdbx-surface { position: relative; flex: 1; min-height: 0; display: grid; grid-template-columns: 228px minmax(230px, .72fr) minmax(350px, 1.28fr); overflow: hidden; background: var(--editorBgColor); color: var(--editorColor); }.kdbx-unlock { grid-column: 1 / -1; display: grid; place-items: center; }.kdbx-unlock-panel { width: min(420px, calc(100vw - 48px)); display: grid; gap: 12px; text-align: center; }.kdbx-unlock-panel h2, .kdbx-unlock-panel p { margin: 0; }.kdbx-unlock-panel h2 { font-size: 24px; }.kdbx-unlock-input { min-width: 0; }.kdbx-unlock-input :deep(.el-input__suffix) { display: flex; align-items: center; gap: 2px; }.kdbx-unlock-action { display: inline-flex; width: 26px; height: 26px; align-items: center; justify-content: center; border: 0; border-radius: 3px; background: transparent; color: var(--editorColor50); cursor: pointer; }.kdbx-unlock-action:hover:not(:disabled) { background: var(--floatHoverColor); color: var(--themeColor); }.kdbx-unlock-action:disabled { cursor: not-allowed; opacity: .45; }.kdbx-return-icon { font-size: 19px; line-height: 1; }.kdbx-error { color: var(--dangerColor, #d14343); }
.kdbx-groups, .kdbx-entries { min-height: 0; border-right: 1px solid var(--itemBgColor); }.kdbx-groups { display: flex; flex-direction: column; overflow: hidden; }.kdbx-entries { overflow: auto; }.kdbx-pane-title, .kdbx-toolbar, .kdbx-detail-title { min-height: 42px; display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 0 10px; border-bottom: 1px solid var(--itemBgColor); }.kdbx-vault-title > span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.kdbx-vault-title > div, .kdbx-detail-title > div:last-child { display: flex; }
button { border: 0; background: transparent; color: inherit; cursor: pointer; } button:disabled { cursor: not-allowed; opacity: .45; }.kdbx-toolbar > button, .kdbx-pane-title button, .kdbx-detail-title button, .kdbx-section-title button, .kdbx-more { display: inline-flex; align-items: center; justify-content: center; flex: 0 0 auto; width: 28px; height: 28px; }.kdbx-toolbar > button:hover, .kdbx-toolbar > button.active, .kdbx-pane-title button:hover, .kdbx-detail-title button:hover, .kdbx-section-title button:hover, .kdbx-more:hover { background: var(--floatHoverColor); }
.kdbx-nav-item { width: 100%; min-height: 34px; display: grid; grid-template-columns: 18px minmax(0, 1fr) auto; gap: 7px; align-items: center; padding: 6px 12px; text-align: left; }.kdbx-nav-item span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.kdbx-nav-item em, .kdbx-tree-label em { color: var(--editorColor50); font-size: 12px; font-style: normal; }.kdbx-nav-item.active, .kdbx-tree-row.active { background: var(--floatHoverColor); color: var(--themeColor); }.kdbx-tree { flex: 1; min-height: 0; overflow: auto; padding: 6px 0; }.kdbx-all-root { display: flex; align-items: stretch; padding-left: 8px; }.kdbx-all-root .kdbx-nav-item { min-width: 0; padding-left: 3px; padding-right: 40px; }.kdbx-all-toggle { display: inline-flex; flex: 0 0 18px; width: 18px; align-items: center; justify-content: center; color: var(--editorColor50); }.kdbx-all-toggle:hover { background: var(--floatHoverColor); color: var(--editorColor); }.kdbx-all-children { padding-left: 20px; }.kdbx-tags { padding-bottom: 6px; margin-bottom: 6px; border-bottom: 1px solid var(--itemBgColor); }.kdbx-tag { padding-left: 9px; padding-right: 40px; color: var(--editorColor50); }.kdbx-tree-row { display: flex; align-items: center; min-height: 30px; padding-right: 7px; }.kdbx-tree-label { min-width: 0; flex: 1; display: grid; grid-template-columns: 17px minmax(0, 1fr) auto; gap: 6px; align-items: center; padding: 5px 3px; text-align: left; }.kdbx-tree-label span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.kdbx-tree-toggle { display: inline-flex; width: 18px; justify-content: center; color: var(--editorColor50); }.kdbx-more { visibility: hidden; }.kdbx-tree-row:hover { background: var(--floatHoverColor); }.kdbx-tree-row:hover .kdbx-more, .kdbx-recycle:hover .kdbx-more { visibility: visible; }.kdbx-recycle { position: relative; display: flex; border-top: 1px solid var(--itemBgColor); }.kdbx-recycle .kdbx-nav-item { padding-right: 34px; }.kdbx-recycle > .kdbx-more { position: absolute; right: 5px; top: 3px; }
.kdbx-toolbar { position: sticky; top: 0; z-index: 1; background: var(--editorBgColor); }.kdbx-toolbar .el-input { min-width: 0; }.kdbx-export-selected { position: relative; }.kdbx-export-selected sup { position: absolute; top: 1px; right: 1px; min-width: 12px; height: 12px; border-radius: 6px; background: var(--themeColor); color: var(--editorBgColor); font-size: 9px; line-height: 12px; text-align: center; }.kdbx-search-options { display: grid; gap: 7px; padding: 10px 12px; border-bottom: 1px solid var(--itemBgColor); background: var(--floatBgColor); font-size: 12px; }.kdbx-search-options :deep(.el-checkbox-group) { display: flex; flex-wrap: wrap; gap: 10px; }.kdbx-search-options :deep(.el-checkbox) { margin-right: 0; }.kdbx-entry-row { display: grid; grid-template-columns: 20px minmax(0, 1fr); gap: 8px; align-items: center; min-height: 56px; padding: 0 12px; border-bottom: 1px solid var(--itemBgColor); }.kdbx-entry-row > button { display: grid; gap: 3px; min-width: 0; min-height: 56px; padding: 9px 0; text-align: left; }.kdbx-entry-row:hover, .kdbx-entry-row.active { background: var(--floatHoverColor); }.kdbx-entry-title, .kdbx-entry-username { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.kdbx-entry-title { font-weight: 600; }.kdbx-entry-username { color: var(--editorColor50); font-size: 12px; }
.kdbx-detail { min-width: 0; overflow: auto; padding: 0 16px 24px; }.kdbx-detail label { display: grid; gap: 6px; margin-top: 14px; font-size: 12px; color: var(--editorColor50); }.kdbx-detail :deep(.el-input__wrapper), .kdbx-detail :deep(.el-select__wrapper), .kdbx-detail :deep(.el-textarea__inner) { background: var(--inputBgColor); box-shadow: 0 0 0 1px var(--floatBorderColor) inset; color: var(--editorColor); }.kdbx-detail :deep(.el-input__inner), .kdbx-detail :deep(.el-textarea__inner), .kdbx-detail :deep(.el-select__selected-item) { color: var(--editorColor80); }.kdbx-detail-title { position: sticky; top: 0; z-index: 2; margin: 0 -16px; padding: 0 16px; background: var(--editorBgColor); }.kdbx-breadcrumb { min-width: 0; display: flex; overflow: hidden; color: var(--editorColor50); font-size: 12px; white-space: nowrap; }.kdbx-breadcrumb span { overflow: hidden; text-overflow: ellipsis; }.kdbx-breadcrumb span + span::before { content: '/'; padding: 0 5px; color: var(--editorColor50); }
.kdbx-section { margin-top: 18px; border-top: 1px solid var(--itemBgColor); padding-top: 10px; }.kdbx-section-title { display: flex; align-items: center; justify-content: space-between; min-height: 28px; }.kdbx-custom-field { display: grid; grid-template-columns: minmax(110px, .6fr) minmax(150px, 1fr) 28px 28px; gap: 6px; align-items: center; margin-top: 7px; }.kdbx-custom-field :deep(.el-checkbox) { display: inline-flex; justify-self: center; width: 28px; height: 28px; margin: 0; }.kdbx-custom-field :deep(.el-checkbox__label) { display: inline-flex; padding-left: 4px; color: var(--editorColor50); }.kdbx-file-input { display: none; }.kdbx-section-empty { padding: 8px 0; color: var(--editorColor50); font-size: 12px; }.kdbx-entry-view { display: grid; grid-template-columns: 116px minmax(0, 1fr); gap: 10px 14px; margin: 16px 0 0; }.kdbx-entry-view dt { color: var(--editorColor50); font-size: 12px; }.kdbx-entry-view dd { min-width: 0; margin: 0; white-space: pre-wrap; overflow-wrap: anywhere; }.kdbx-custom-field-view { margin-top: 10px; }.kdbx-tag-chip { display: inline-flex; margin: 0 5px 4px 0; padding: 2px 7px; border: 1px solid var(--floatBorderColor); border-radius: 3px; background: var(--floatHoverColor); color: var(--editorColor); font-size: 12px; }.kdbx-attachment { display: flex; align-items: center; gap: 4px; min-height: 32px; }.kdbx-attachment > div { min-width: 0; flex: 1; display: grid; grid-template-columns: 17px minmax(0, 1fr) auto; gap: 6px; align-items: center; text-align: left; }.kdbx-attachment span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.kdbx-attachment em { color: var(--editorColor50); font-size: 12px; font-style: normal; }.kdbx-attachment > button { display: inline-flex; width: 28px; height: 28px; align-items: center; justify-content: center; }.kdbx-attachment:hover { background: var(--floatHoverColor); }.kdbx-attachment-preview { display: block; width: auto; max-width: 100%; height: auto; max-height: calc(100vh - 180px); margin: 0 auto; object-fit: contain; }
.kdbx-history-row { display: grid; grid-template-columns: minmax(0, 1fr) auto auto auto; gap: 8px; align-items: center; min-height: 43px; border-bottom: 1px solid var(--itemBgColor); }.kdbx-history-row > div { min-width: 0; display: grid; gap: 2px; }.kdbx-history-row strong, .kdbx-history-row span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.kdbx-history-row span { color: var(--editorColor50); font-size: 11px; }.kdbx-history-row > button { padding: 4px 6px; color: var(--themeColor); font-size: 12px; }.kdbx-history-delete { display: inline-flex; width: 28px; height: 28px; align-items: center; justify-content: center; padding: 0 !important; color: var(--editorColor50) !important; }.kdbx-history-row > button:hover { background: var(--floatHoverColor); }.kdbx-empty { display: grid; place-items: center; min-height: 120px; color: var(--editorColor50); }.kdbx-group-menu { position: fixed; z-index: 30; display: grid; min-width: 142px; padding: 4px; border: 1px solid var(--floatBorderColor); background: var(--floatBgColor); box-shadow: 0 5px 16px rgb(0 0 0 / 18%); }.kdbx-group-menu button { display: grid; grid-template-columns: 18px 1fr; gap: 7px; align-items: center; padding: 7px; text-align: left; font-size: 13px; }.kdbx-group-menu button:hover { background: var(--floatHoverColor); }.kdbx-history-preview { display: grid; grid-template-columns: 110px minmax(0, 1fr); gap: 10px 14px; margin: 0; }.kdbx-history-preview dt { color: var(--editorColor50); }.kdbx-history-preview dd { min-width: 0; margin: 0; white-space: pre-wrap; overflow-wrap: anywhere; }.kdbx-edit-form { display: grid; gap: 14px; }.kdbx-edit-form > label { display: grid; gap: 6px; color: var(--editorColor50); font-size: 12px; }.kdbx-edit-form :deep(.el-input__wrapper), .kdbx-edit-form :deep(.el-select__wrapper), .kdbx-edit-form :deep(.el-textarea__inner) { background: var(--inputBgColor); box-shadow: 0 0 0 1px var(--floatBorderColor) inset; color: var(--editorColor); }.kdbx-edit-form :deep(.el-input__inner), .kdbx-edit-form :deep(.el-textarea__inner), .kdbx-edit-form :deep(.el-select__selected-item) { color: var(--editorColor80); }.kdbx-password-view { display: flex; align-items: center; gap: 6px; }.kdbx-password-view > span { min-width: 0; flex: 1; }.kdbx-password-view > button { display: inline-flex; width: 28px; height: 28px; align-items: center; justify-content: center; color: var(--editorColor50); }.kdbx-password-view > button:hover { background: var(--floatHoverColor); color: var(--editorColor); } @media (max-width: 900px) { .kdbx-surface { grid-template-columns: 190px minmax(0, 1fr); }.kdbx-detail { display: none; } }
</style>
